In [1]:
from sklearn.datasets import load_iris
import skfuzzy as fuzz
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')

data = load_iris()
X = data.data
# Adding random features to X
X = np.hstack((X,30*np.ones((len(X),1))))
Y = data.target

In [2]:
cntr, u, u0, d, jm, p, fpc = fuzz.cluster.cmeans(X.T, 3, 60, error=0.0001, maxiter=100000, init=None)
metrics.adjusted_rand_score(Y,np.argmax(u,axis=0))

0.78592653061224493

# Creating the CF Matrix

In [3]:
clu = 1
CF = np.zeros((X.shape[1],X.shape[1]))
for i in range(X.shape[1]):
    for j in range(X.shape[1]):
        summ=0
        for d in range(X.shape[0]):
            if np.argmax(u[:,d]) == clu:
                summ+=X[d][i]*X[d][j]
        CF[i,j]=summ

# Normalization

In [4]:
NCF = np.zeros((X.shape[1],X.shape[1]))
for i in range(X.shape[1]):
    for j in range(X.shape[1]):
        NCF[i,j]=CF[i,j]/(CF[i,j]+CF[j,j]-CF[i,j])

# Centroid

In [5]:
SC = np.zeros(X.shape[1])
for i in range(X.shape[1]):
    SC[i] = np.sum(NCF[i,:])


# Cosine Similarity to select top features

In [6]:
cosim = cosine_similarity(SC,CF)
print(cosim)
top = 4
print("Top features are: ",(-cosim).argsort()[0][:top])

[[ 0.99999928  0.99999946  0.99999991  0.99999964  0.999998  ]]
Top features are:  [2 3 1 0]


In [15]:
def selecttop(CF, k, X = None):
    NCF = np.zeros((CF.shape[1],CF.shape[1]))
    for i in range(CF.shape[1]):
        for j in range(CF.shape[1]):
            NCF[i,j]=CF[i,j]/(CF[i,j]+CF[j,j]-CF[i,j])
            
    SC = np.zeros(CF.shape[1])
    for i in range(CF.shape[1]):
        SC[i] = np.sum(NCF[i,:])
        
    cosim = cosine_similarity(SC,CF)
    if X == None:
        return (-cosim).argsort()[0][:int(k*CF.shape[1])]
        
    # Not in the same order
    return X[:,selecttop(CF,.8)]

In [16]:
selecttop(CF,.8)

array([2, 3, 1, 0])

In [17]:
print(selecttop(CF,.8, X))

[[ 1.4  0.2  3.5  5.1]
 [ 1.4  0.2  3.   4.9]
 [ 1.3  0.2  3.2  4.7]
 [ 1.5  0.2  3.1  4.6]
 [ 1.4  0.2  3.6  5. ]
 [ 1.7  0.4  3.9  5.4]
 [ 1.4  0.3  3.4  4.6]
 [ 1.5  0.2  3.4  5. ]
 [ 1.4  0.2  2.9  4.4]
 [ 1.5  0.1  3.1  4.9]
 [ 1.5  0.2  3.7  5.4]
 [ 1.6  0.2  3.4  4.8]
 [ 1.4  0.1  3.   4.8]
 [ 1.1  0.1  3.   4.3]
 [ 1.2  0.2  4.   5.8]
 [ 1.5  0.4  4.4  5.7]
 [ 1.3  0.4  3.9  5.4]
 [ 1.4  0.3  3.5  5.1]
 [ 1.7  0.3  3.8  5.7]
 [ 1.5  0.3  3.8  5.1]
 [ 1.7  0.2  3.4  5.4]
 [ 1.5  0.4  3.7  5.1]
 [ 1.   0.2  3.6  4.6]
 [ 1.7  0.5  3.3  5.1]
 [ 1.9  0.2  3.4  4.8]
 [ 1.6  0.2  3.   5. ]
 [ 1.6  0.4  3.4  5. ]
 [ 1.5  0.2  3.5  5.2]
 [ 1.4  0.2  3.4  5.2]
 [ 1.6  0.2  3.2  4.7]
 [ 1.6  0.2  3.1  4.8]
 [ 1.5  0.4  3.4  5.4]
 [ 1.5  0.1  4.1  5.2]
 [ 1.4  0.2  4.2  5.5]
 [ 1.5  0.1  3.1  4.9]
 [ 1.2  0.2  3.2  5. ]
 [ 1.3  0.2  3.5  5.5]
 [ 1.5  0.1  3.1  4.9]
 [ 1.3  0.2  3.   4.4]
 [ 1.5  0.2  3.4  5.1]
 [ 1.3  0.3  3.5  5. ]
 [ 1.3  0.3  2.3  4.5]
 [ 1.3  0.2  3.2  4.4]
 [ 1.6  0.6